version: '2'
services:
  web:
    build: .
    # command: flask run -h 0.0.0.0 --reload
    command: python run.py
    volumes:
      - .:/usr/app/
    ports:
      - 5000:5000
    environment: 
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - SECRET=NPH2xmMIKI78gsIZ/BPCCpy6u6MnLbFhT4Oj1S/zky0=
      - DATABASE_URI=postgresql://postgres:secret@db:5432/patients
      - DATABASE_TEST_URL=postgresql://postgres:secret@db:5432/patients_test
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  